const fs = require('fs');
const path = require('path');

const docsDir = path.join(__dirname, 'docs');
const outputFilename = path.join(__dirname, 'Rideal_Postman_Collection.json');

const collection = {
    info: {
        name: "Rideal Multi-Vendor Delivery Platform APIs",
        description: "Autogenerated single source of truth from Markdown documentation.",
        schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    item: []
};

// Simple curl parser
function parseCurl(curlString) {
    let method = 'GET';
    const methodMatch = curlString.match(/-X\s+([A-Z]+)/);
    if (methodMatch) {
        method = methodMatch[1];
    }

    let url = '';
    const urlMatch = curlString.match(/http:\/\/localhost:6030[^\s\'\"\\]+/);
    if (urlMatch) {
        url = urlMatch[0];
    }

    const headers = [];
    const headerRegex = /-H\s+"([^"]+)"/g;
    let match;
    while ((match = headerRegex.exec(curlString)) !== null) {
        const parts = match[1].split(':');
        if (parts.length >= 2) {
            headers.push({
                key: parts[0].trim(),
                value: parts.slice(1).join(':').trim()
            });
        }
    }

    let bodyRaw = '';
    const bodyMatch = curlString.match(/-d\s+'([^']+)'/);
    if (bodyMatch) {
        bodyRaw = bodyMatch[1];
        if (!methodMatch) method = 'POST'; // curl defaults to POST if -d is present
    } else {
      // maybe it's in double quotes? 
      // This is basic and might need tweaking based on exact formats, but docs use single quotes for -d
    }

    return { method, url, headers, bodyRaw };
}

fs.readdirSync(docsDir).forEach(file => {
    if (!file.endsWith('.md')) return;
    
    const content = fs.readFileSync(path.join(docsDir, file), 'utf8');
    const folderName = file.replace('.md', '').split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    
    const folder = {
        name: folderName,
        item: []
    };

    // Find all bold titles followed by a bash block with curl
    // Accounts for both LF and CRLF line endings
    const regex = /\*\*([^*]+)\*\*[\s\S]*?```bash\r?\n(curl[\s\S]*?)\r?\n```/g;
    
    let match;
    while ((match = regex.exec(content)) !== null) {
        const reqName = match[1].trim();
        const curlContent = match[2];
        
        const parsed = parseCurl(curlContent);
        
        if (parsed.url) {
            const urlParts = parsed.url.replace('http://', '').split('/');
            const host = urlParts[0].split(':');
            const pathArr = urlParts.slice(1);
            
            const postmanReq = {
                name: reqName,
                request: {
                    method: parsed.method,
                    header: parsed.headers,
                    url: {
                        raw: parsed.url,
                        protocol: "http",
                        host: [host[0]],
                        port: host[1] || "80",
                        path: pathArr
                    }
                },
                response: []
            };

            if (parsed.bodyRaw) {
                postmanReq.request.body = {
                    mode: "raw",
                    raw: parsed.bodyRaw,
                    options: {
                        raw: {
                            language: "json"
                        }
                    }
                };
            }
            
            folder.item.push(postmanReq);
        }
    }
    
    if (folder.item.length > 0) {
        collection.item.push(folder);
    }
});

fs.writeFileSync(outputFilename, JSON.stringify(collection, null, 2));
console.log('Postman collection generated at:', outputFilename);
